source:      .
destination: ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         /console-browsers
lsi:         false
