source:      .
destination: ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
include:     ['.htaccess']
exclude:     []
keep_files:  ['.git','.svn']
timezone:    nil
description: Stats on game console browsers

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         /console-browsers
lsi:         false

sass:
  sass_dir: style/_sass
  style: compressed

collections:
  device:
    output: true
    permalink: /device/:path
