<ul class="nav nav-list well">
	<li class="nav-header">TV Consoles</li>
		<li><a href="/device/xbox360.php">Microsoft Xbox 360</a></li>
		<li><a href="/device/ps3.php">Sony PS3</a></li>
		<li><a href="/device/wii.php">Nintendo Wii</a></li>
		<li><a href="/device/wiiu.php">Nintendo Wii U</a></li>
	<li class="divider"></li>
	<li class="nav-header">Portable Consoles</li>
		<li><a href="/device/psp-1000.php">Sony PSP-1000</a></li>
		<li class="inactive">Sony PSP-2000 (untested)</li>
		<li class="inactive">Sony PSP-3000 (untested)</li>
		<li class="inactive">Sony PSP Go (untested)</li>
		<li><a href="/device/psvita.php">Sony PS Vita</a></li>
		<li><a href="/device/ds.php">Nintendo DS</a></li>
		<li class="inactive">Nintendo DS Lite (untested)</li>
		<li><a href="/device/dsi.php">Nintendo DSi</a></li>
		<li class="inactive">Nintendo DSi XL (untested)</li>
		<li class="inactive">Nintendo 3DS (untested)</li>
		<li><a href="/device/3dsxl.php">Nintendo 3DS XL</a></li>
	<li class="divider"></li>
	<li class="nav-header">Hybrid Phone/Portable Consoles</li>
		<li><a href="/device/xperiaplay.php">Xperia Play</a></li>
	<li class="divider"></li>
	<li class="nav-header">Smart TVs</li>
		<li><a href="/device/vizio-costar.php">Vizio Co-Star</a></li>
	<li class="divider"></li>
	<li class="nav-header">Waiting for official release</li>
		<li class="inactive">Ouya</li>
		<li class="inactive">Razer Switchblade</li>
		<li class="inactive">Razer Edge</li>
		<li class="inactive">Nvidia's Project Shield</li>
		<li class="inactive">Valve's Steam Box</li>
</ul>